default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: surakshya
  password: 2026
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: leave_management_system_development

test:
  <<: *default
  database: leave_management_system_test

production:
  <<: *default
  database: leave_management_system_production
  username: surakshya
  password: 2026
